import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, HydratedDocument } from 'mongoose';

export type IssuerApplicationDocument = HydratedDocument<IssuerApplication>;

export enum AssetCategory {
  REAL_ESTATE = 'Real Estate',
  COMMODITIES = 'Commodities',
  COMPANY_EQUITY = 'Company Equity',
  ART_COLLECTIBLES = 'Art & Collectibles',
  INTELLECTUAL_PROPERTY = 'Intellectual Property',
  OTHER = 'Other',
}

export enum ApplicationStatus {
  PENDING = 'pending',
  UNDER_REVIEW = 'under_review',
  APPROVED = 'approved',
  REJECTED = 'rejected',
  REQUIRES_MORE_INFO = 'requires_more_info',
}

@Schema({
  collection: 'issuer_applications',
  timestamps: true,
  toJSON: {
    virtuals: true,
    transform: (_, ret: Record<string, unknown>) => {
      delete ret.__v;
      return ret;
    },
  },
})
export class IssuerApplication extends Document {
  @Prop({ required: true, trim: true })
  applicationId: string;

  @Prop({ required: true, trim: true })
  userId: string;

  @Prop({ lowercase: true, trim: true })
  email?: string;

  @Prop({ trim: true })
  phoneNumber?: string;


  @Prop({ trim: true })
  phoneCountryCode?: string;

  @Prop({ required: true, trim: true, minlength: 2 })
  legalEntityName: string;

  @Prop({ required: true, trim: true, minlength: 2 })
  countryOfIncorporation: string;

  @Prop({ required: true, type: String, enum: AssetCategory })
  assetCategory: AssetCategory;

  @Prop({ required: true, trim: true, minlength: 10 })
  shortAssetDescription: string;

  @Prop({
    type: String,
    enum: ApplicationStatus,
    default: ApplicationStatus.PENDING,
  })
  status: ApplicationStatus;

  @Prop()
  reviewedAt?: Date;

  @Prop()
  reviewNotes?: string;

  @Prop()
  rejectionReason?: string;

  @Prop({ type: Object })
  metadata?: Record<string, any>;

  // Timestamps (auto-generated by Mongoose)
  createdAt: Date;
  updatedAt: Date;
}

export const IssuerApplicationSchema = SchemaFactory.createForClass(IssuerApplication);

// Indexes for efficient querying
IssuerApplicationSchema.index({ applicationId: 1 }, { unique: true });
IssuerApplicationSchema.index({ userId: 1 });
IssuerApplicationSchema.index({ email: 1 });
IssuerApplicationSchema.index({ status: 1 });
IssuerApplicationSchema.index({ assetCategory: 1 });
IssuerApplicationSchema.index({ legalEntityName: 'text', shortAssetDescription: 'text' });
IssuerApplicationSchema.index({ createdAt: -1 });
IssuerApplicationSchema.index({ countryOfIncorporation: 1 });

// Compound index for common queries
IssuerApplicationSchema.index({ userId: 1, status: 1 });
IssuerApplicationSchema.index({ status: 1, createdAt: -1 });
IssuerApplicationSchema.index({ assetCategory: 1, status: 1 });
