import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, HydratedDocument } from 'mongoose';

export type IssuerUserDocument = HydratedDocument<IssuerUser>;

export enum KYCStatus {
  PENDING = 'pending',
  APPROVED = 'approved',
  REJECTED = 'rejected',
}

@Schema({
  collection: 'issuerprofiles',
  timestamps: true,
  toJSON: {
    virtuals: true,
    transform: (_, ret: Record<string, unknown>) => {
      delete ret.password;
      delete ret.__v;
      return ret;
    },
  },
})
export class IssuerUser extends Document {
  @Prop({ required: true, lowercase: true, trim: true })
  email: string;



  @Prop({ trim: true })
  firstName?: string;
  @Prop({ trim: true })
  lastName?: string;


  @Prop({ trim: true })
  phoneNumber?: string;

  @Prop({ type: Object })
  metadata?: Record<string, any>;

  @Prop({ trim: true })
  kycStatus?: KYCStatus;
  // Timestamps (auto-generated by Mongoose)
  createdAt: Date;
  updatedAt: Date;
}

export const IssuerUserSchema = SchemaFactory.createForClass(IssuerUser);

// Indexes
IssuerUserSchema.index({ email: 1 }, { unique: true });
IssuerUserSchema.index({ createdAt: -1 });

